# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19008b50ba3aa39f583ac4c3ddf0a95bce8b2e74bd8b44b13eb989ecad185b77b47dcc1d2799f67fd6df8ff2b6fc30ef9f164f780264a0c3816b9fff571b8ad

test:
  secret_key_base: aa577b8ce91bf99dfd584e8f584540e7bd474b7e02b93de91a55952acf3ed0ed428a7c605c302ef31598cf0a18a876333c35c91061c3f1304face1c51e31b782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
